apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: delschcrud
  namespace: edppublic-delschcrud-dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:edppublic-*
spec:
  releaseName: delschcrud
  chart:
    git: git@github.com:prasantabarik/DeliveryScheduleCRUD
    path: deploy-templates
    ref: master
  values:
    name: delschcrud
    group: delschcrud
    namespace: edppublic-delschcrud-dev
    image:
      name: weeus01devakscn01.azurecr.io/edppublic/delschcrud-master
      version: 1.0.0-SNAPSHOT.4
    replicaCount: 1
      
